version: '3.8'
services:
  almalinux_httpd:
    image: httpd:latest
    container_name: almalinux_apache-container
    ports:
    - "8872:80"
    volumes:
    - hosting_data:/data
    networks:
    - network1
volumes:
  hosting_data:
networks:
  network1:
    name: network1
    driver: bridge

