version: '3.8'

services:
  mariadb-container:
    image: mariadb:latest
    ports:
    - "8889:3306"
    environment:
      MARIADB_ROOT_PASSWORD: "1234"
    volumes:
    - database_data:/var/lib/mysql
    networks:
    - network1
volumes:
  database_data:
networks:
  network1:

