version: '3.8'

services:
  redis_database:
    image: redis:latest
    container_name: redis-container
    ports:
    - "6379:6379"
    volumes:
    - database_data:/data
    networks:
    - network1
volumes:
  database_data:
networks:
  network1:

